/**
 * AUTO-GENERATED by scripts/fetch-home-data.mjs
 * Last updated: 2026-04-04T12:08:18.462Z
 *
 * DO NOT edit manually.
 * To regenerate : node scripts/fetch-home-data.mjs
 * To restore    : git checkout client/src/data/homeContentDynamic.ts
 */

import type { HeroSlide, Product } from '../types';

export const heroSlides: HeroSlide[] = [
  {
    "image": "https://drive.usercontent.google.com/download?id=11Vw0LVrrg8h1Em-ZazrM-xDYQ6G1UwEW&export=view",
    "quote": "Premium rides for South Tamil Nadu."
  },
  {
    "image": "https://drive.usercontent.google.com/download?id=1MEc3QsOiuZn6Y6TNlYm_6PbUpDa4V2AW&export=view",
    "quote": "Tirunelveli’s best cycles. Start your adventure."
  },
  {
    "image": "https://drive.usercontent.google.com/download?id=1E8myMYG7v7WEeYK7En4CICut3QZYThh9&export=view",
    "quote": "Ride together. Grow together."
  },
  {
    "image": "https://drive.usercontent.google.com/download?id=123t3VquPPEvK83UGPi56gfX3wuD_Eg-w&export=view",
    "quote": "Go faster with KTR Cycle World."
  }
];

export const popularProducts: Product[] = [
  {
    "id": "prod_002",
    "product_id": "prod_002",
    "name": " SKYWALK 20\"\n",
    "brand": "TORONTO",
    "image": "https://drive.usercontent.google.com/download?id=1eBNB7OMAojPoyJ8L5cC1YdaVpJ-6ot3j&export=view",
    "images": "https://drive.google.com/file/d/1eBNB7OMAojPoyJ8L5cC1YdaVpJ-6ot3j/view?usp=sharing",
    "category": "cat_001",
    "category_id": "cat_001",
    "category_name": "",
    "age_group": "",
    "color": "",
    "original_price": 11200,
    "discounted_price": 11200,
    "discount_percent": 0,
    "discount": 0,
    "stock": 3,
    "featured": true,
    "location": "Tirunelveli",
    "short_description": "kids cycle for 7 TO 11 years",
    "long_description": "",
    "description": "kids cycle for 7 TO 11 years",
    "tags": "KIDS CYCLE",
    "varient_label": "TORONTO SKYWALK 20\"\n",
    "specifications": "",
    "features": "",
    "currentPrice": 11200,
    "rating": 0,
    "reviews": 0
  },
  {
    "id": "prod_007",
    "product_id": "prod_007",
    "name": "Alpha Serenity 26",
    "brand": "ALPHA",
    "image": "https://drive.usercontent.google.com/download?id=1M-yk3ykdEjwWEFbJvflje08gd41UBtlD&export=view",
    "images": "https://drive.google.com/file/d/1M-yk3ykdEjwWEFbJvflje08gd41UBtlD/view?usp=drivesdk",
    "category": "cat_004",
    "category_id": "cat_004",
    "category_name": "",
    "age_group": "",
    "color": "",
    "original_price": 7800,
    "discounted_price": 7550,
    "discount_percent": 3.21,
    "discount": 3.21,
    "stock": 1,
    "featured": true,
    "location": "Tirunelveli",
    "short_description": "",
    "long_description": "",
    "description": "",
    "tags": "LADIES CYCLE",
    "varient_label": "Alpha Serenity 26 7800",
    "specifications": "",
    "features": "",
    "currentPrice": 7550,
    "rating": 0,
    "reviews": 0
  },
  {
    "id": "prod_014",
    "product_id": "prod_014",
    "name": "BSA Champ 12T",
    "brand": "hercules",
    "image": "https://drive.usercontent.google.com/download?id=1Tc2Hs4cDQLCKU6TtypWXwS1aoqQzb6gH&export=view",
    "images": "https://drive.google.com/file/d/1Tc2Hs4cDQLCKU6TtypWXwS1aoqQzb6gH/view?usp=drivesdk",
    "category": "cat_001",
    "category_id": "cat_001",
    "category_name": "",
    "age_group": "",
    "color": "",
    "original_price": 4400,
    "discounted_price": 4150,
    "discount_percent": 5.68,
    "discount": 5.68,
    "stock": 3,
    "featured": true,
    "location": "Tirunelveli",
    "short_description": "kids cycle for under 5 years",
    "long_description": "",
    "description": "kids cycle for under 5 years",
    "tags": "KIDS CYCLE",
    "varient_label": "BSA Champ 12T",
    "specifications": "",
    "features": "",
    "currentPrice": 4150,
    "rating": 0,
    "reviews": 0
  },
  {
    "id": "prod_028",
    "product_id": "prod_028",
    "name": "WIFI Domain 29T",
    "brand": "WIFI",
    "image": "https://drive.usercontent.google.com/download?id=1sD65QvjXvGthjS4uxHz6OUzAovwq3Qu4&export=view",
    "images": "https://drive.google.com/file/d/1sD65QvjXvGthjS4uxHz6OUzAovwq3Qu4/view?usp=drivesdk",
    "category": "cat_003",
    "category_id": "cat_003",
    "category_name": "",
    "age_group": "",
    "color": "",
    "original_price": 19000,
    "discounted_price": 18750,
    "discount_percent": 1.32,
    "discount": 1.32,
    "stock": 3,
    "featured": true,
    "location": "Tirunelveli",
    "short_description": "All our frames for MTBs are made of high-tensile steel, the tyres are hartex-hi traction tyres, and the rims are made of double-wall alloys.",
    "long_description": "",
    "description": "All our frames for MTBs are made of high-tensile steel, the tyres are hartex-hi traction tyres, and the rims are made of double-wall alloys.",
    "tags": "GEAR CYCLE",
    "varient_label": "WIFI Domain 29T",
    "specifications": "",
    "features": "",
    "currentPrice": 18750,
    "rating": 0,
    "reviews": 0
  },
  {
    "id": "prod_033",
    "product_id": "prod_033",
    "name": "HERCULES REDEEM 27T DD 21S",
    "brand": "HERCULES",
    "image": "https://drive.usercontent.google.com/download?id=1AAIyUzHG5doVW3ngPegJyohnF5E7bPPa&export=view",
    "images": "https://drive.google.com/file/d/1AAIyUzHG5doVW3ngPegJyohnF5E7bPPa/view?usp=sharing",
    "category": "cat_003",
    "category_id": "cat_003",
    "category_name": "",
    "age_group": "",
    "color": "",
    "original_price": 13500,
    "discounted_price": 13250,
    "discount_percent": 1.85,
    "discount": 1.85,
    "stock": 2,
    "featured": true,
    "location": "Tirunelveli",
    "short_description": "",
    "long_description": "",
    "description": "",
    "tags": "GEAR",
    "varient_label": "HERCULES",
    "specifications": "",
    "features": "",
    "currentPrice": 13250,
    "rating": 0,
    "reviews": 0
  }
];
